"use client";
import { useCallback, useEffect, useState } from "react";
import type { ModuleEntitlement } from "@/lib/auth/domain";

type EventSummary={id:string;name:string;event_date:string};
type Grant={id:string;eventName:string;workerLabel:string;entitlements:ModuleEntitlement[];status:string;expiresAt:string;code?:string};

export default function EventAccessManagement({active}:{active:boolean}){
  const [event,setEvent]=useState<EventSummary|null>(null);const [grants,setGrants]=useState<Grant[]>([]);const [name,setName]=useState("");const [hours,setHours]=useState(12);const [vendor,setVendor]=useState(true);const [inventory,setInventory]=useState(true);const [issued,setIssued]=useState<Grant|null>(null);const [message,setMessage]=useState<string|null>(null);
  const load=useCallback(async()=>{if(!active)return;const response=await fetch("/api/administration/event-access",{cache:"no-store"});if(!response.ok){setMessage("Event access could not be loaded.");return;}const body=await response.json() as {event:EventSummary|null;grants:Grant[]};setEvent(body.event);setGrants(body.grants)},[active]);
  useEffect(()=>{if(!active)return;let cancelled=false;void fetch("/api/administration/event-access",{cache:"no-store"}).then(async response=>{if(!response.ok)throw new Error();return response.json() as Promise<{event:EventSummary|null;grants:Grant[]}>}).then(body=>{if(!cancelled){setEvent(body.event);setGrants(body.grants)}}).catch(()=>{if(!cancelled)setMessage("Event access could not be loaded.")});return()=>{cancelled=true}},[active]);
  async function create(e:React.FormEvent){e.preventDefault();if(!event)return;const entitlements:ModuleEntitlement[]=[];if(vendor)entitlements.push({module:"VENDOR_WORKSPACE",access:"OPERATE"});if(inventory)entitlements.push({module:"INVENTORY",access:"OPERATE"});setMessage("Generating secure code…");setIssued(null);const response=await fetch("/api/administration/event-access",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({eventId:event.id,workerLabel:name,durationHours:hours,entitlements})});const body=await response.json().catch(()=>({})) as Grant&{error?:string};if(!response.ok){setMessage(body.error??"Code could not be generated.");return;}setIssued(body);setName("");setMessage("Code generated. It is shown only now; send it privately to the worker.");await load()}
  async function revoke(id:string){const response=await fetch(`/api/administration/event-access?id=${encodeURIComponent(id)}`,{method:"DELETE"});setMessage(response.ok?"Worker access revoked.":"Access could not be revoked.");await load()}
  return <section className="rounded-xl border border-zinc-800 bg-zinc-900/60 p-5" aria-labelledby="event-access-title"><p className="text-xs font-semibold uppercase tracking-[.18em] text-cyan-300">Event security</p><h3 id="event-access-title" className="mt-2 text-lg font-semibold text-white">Timed worker login</h3><p className="mt-2 text-sm leading-6 text-zinc-400">Generate account-free access for event staff. Access ends at the selected time, when revoked, or immediately when the event closes.</p>
  {!active?<p className="mt-4 rounded-lg border border-amber-400/25 bg-amber-400/10 p-4 text-sm text-amber-100">Configure private authentication before issuing worker access.</p>:!event?<p className="mt-4 rounded-lg border border-zinc-700 p-4 text-sm text-zinc-300">Start an Event Ledger event before generating a worker code.</p>:<form onSubmit={create} className="mt-5 space-y-4"><p className="rounded-lg border border-cyan-900 bg-cyan-950/20 p-3 text-sm text-cyan-100"><strong>{event.name}</strong> · active event</p><div className="grid gap-3 sm:grid-cols-[minmax(0,1fr)_9rem]"><label className="text-sm text-zinc-300">Worker name or station<input required minLength={2} maxLength={80} value={name} onChange={e=>setName(e.target.value)} placeholder="Front case — Ana" className="mt-1 min-h-11 w-full rounded-lg border border-zinc-700 bg-zinc-950 px-3 text-white" /></label><label className="text-sm text-zinc-300">Duration<select value={hours} onChange={e=>setHours(Number(e.target.value))} className="mt-1 min-h-11 w-full rounded-lg border border-zinc-700 bg-zinc-950 px-3 text-white">{[1,2,4,8,12,16,24].map(value=><option key={value} value={value}>{value} hours</option>)}</select></label></div><fieldset><legend className="text-sm text-zinc-300">Operational access</legend><div className="mt-2 flex flex-wrap gap-4"><label className="flex min-h-11 items-center gap-2 text-sm text-zinc-200"><input type="checkbox" checked={vendor} onChange={e=>setVendor(e.target.checked)} /> Vendor Workspace</label><label className="flex min-h-11 items-center gap-2 text-sm text-zinc-200"><input type="checkbox" checked={inventory} onChange={e=>setInventory(e.target.checked)} /> Inventory / Display Case</label></div></fieldset><button className="min-h-11 rounded-lg bg-cyan-300 px-4 font-semibold text-zinc-950">Generate event code</button></form>}
  {message?<p role="status" className="mt-3 text-sm text-zinc-400">{message}</p>:null}{issued?.code?<div className="mt-4 rounded-lg border border-cyan-700 bg-cyan-950/30 p-4"><p className="text-xs font-semibold uppercase tracking-wide text-cyan-300">Single-use worker code</p><p className="mt-2 font-mono text-xl tracking-widest text-white">{issued.code}</p><div className="mt-3 flex flex-wrap gap-2"><button type="button" onClick={()=>void navigator.clipboard.writeText(issued.code!)} className="min-h-11 rounded-lg border border-cyan-700 px-4 text-sm font-semibold text-cyan-100">Copy code</button><button type="button" onClick={()=>void navigator.clipboard.writeText(`${window.location.origin}/event-access`)} className="min-h-11 rounded-lg border border-zinc-700 px-4 text-sm text-zinc-200">Copy login link</button></div></div>:null}
  {grants.length?<div className="mt-6 space-y-3"><h4 className="text-sm font-semibold text-zinc-200">Issued event access</h4>{grants.map(grant=><article key={grant.id} className="flex flex-wrap items-center justify-between gap-3 rounded-lg border border-zinc-800 bg-zinc-950/70 p-4"><div><p className="font-medium text-white">{grant.workerLabel}</p><p className="mt-1 text-xs text-zinc-400">{grant.status.replaceAll("_"," ")} · until {new Date(grant.expiresAt).toLocaleString()}</p><p className="mt-1 text-xs text-zinc-500">{grant.entitlements.map(x=>x.module.replaceAll("_"," ")).join(" · ")}</p></div>{(grant.status==="ACTIVE"||grant.status==="REDEEMED")?<button type="button" onClick={()=>void revoke(grant.id)} className="min-h-11 rounded-lg border border-red-900 px-4 text-sm text-red-200">Revoke</button>:null}</article>)}</div>:null}</section>
}
